In [2]:
###replace directories for SIMI_SACT_TUMOUR for synthetic data###

import pandas as pd
import numpy as np

##import SIM I data and create subsets with random selection
SIMI_SACT_TUMOUR=pd.read_table("simulacrum_release_v1/sim_sact_tumour.csv", sep=",")
SIMI_SACT_TUMOUR_50 = SIMI_SACT_TUMOUR.sample(frac =.50)
SIMI_SACT_TUMOUR_25 = SIMI_SACT_TUMOUR.sample(frac =.25)
SIMI_SACT_TUMOUR_10 = SIMI_SACT_TUMOUR.sample(frac =.10)

##new table with counts of unique data
SIMI_SACT_TUMOUR_unique =pd.DataFrame({'Item': ['PRIMARY_DIAGNOSIS', 'CONSULTANT_SPECIALITY_CODE','MORPHOLOGY_CLEAN'], 
                      'Syhtnetic_data_unique_count': [SIMI_SACT_TUMOUR['PRIMARY_DIAGNOSIS'].nunique(), SIMI_SACT_TUMOUR['CONSULTANT_SPECIALITY_CODE'].nunique(),SIMI_SACT_TUMOUR['MORPHOLOGY_CLEAN'].nunique()],
                      '0.50_Syhtnetic_data_unique_count': [SIMI_SACT_TUMOUR_50['PRIMARY_DIAGNOSIS'].nunique(), SIMI_SACT_TUMOUR_50['CONSULTANT_SPECIALITY_CODE'].nunique(), SIMI_SACT_TUMOUR_50['MORPHOLOGY_CLEAN'].nunique()],
                     '0.25_Syhtnetic_data_unique_count': [SIMI_SACT_TUMOUR_25['PRIMARY_DIAGNOSIS'].nunique(), SIMI_SACT_TUMOUR_25['CONSULTANT_SPECIALITY_CODE'].nunique(), SIMI_SACT_TUMOUR_25['MORPHOLOGY_CLEAN'].nunique()],
                    '0.10_Syhtnetic_data_unique_count': [SIMI_SACT_TUMOUR_10['PRIMARY_DIAGNOSIS'].nunique(), SIMI_SACT_TUMOUR_10['CONSULTANT_SPECIALITY_CODE'].nunique(), SIMI_SACT_TUMOUR_10['MORPHOLOGY_CLEAN'].nunique()]
                                      })
SIMI_SACT_TUMOUR_unique['Missing_values_0.50_count']=SIMI_SACT_TUMOUR_unique['Syhtnetic_data_unique_count']-SIMI_SACT_TUMOUR_unique['0.50_Syhtnetic_data_unique_count']
SIMI_SACT_TUMOUR_unique['Missing_values_0.50_percentage']=(SIMI_SACT_TUMOUR_unique['Syhtnetic_data_unique_count']-SIMI_SACT_TUMOUR_unique['0.50_Syhtnetic_data_unique_count'])/SIMI_SACT_TUMOUR_unique['Syhtnetic_data_unique_count']*100
SIMI_SACT_TUMOUR_unique['Missing_values_0.25_count']=SIMI_SACT_TUMOUR_unique['Syhtnetic_data_unique_count']-SIMI_SACT_TUMOUR_unique['0.25_Syhtnetic_data_unique_count']
SIMI_SACT_TUMOUR_unique['Missing_values_0.25_percentage']=(SIMI_SACT_TUMOUR_unique['Syhtnetic_data_unique_count']-SIMI_SACT_TUMOUR_unique['0.25_Syhtnetic_data_unique_count'])/SIMI_SACT_TUMOUR_unique['Syhtnetic_data_unique_count']*100
SIMI_SACT_TUMOUR_unique['Missing_values_0.10_count']=SIMI_SACT_TUMOUR_unique['Syhtnetic_data_unique_count']-SIMI_SACT_TUMOUR_unique['0.10_Syhtnetic_data_unique_count']
SIMI_SACT_TUMOUR_unique['Missing_values_0.10_percentage']=(SIMI_SACT_TUMOUR_unique['Syhtnetic_data_unique_count']-SIMI_SACT_TUMOUR_unique['0.10_Syhtnetic_data_unique_count'])/SIMI_SACT_TUMOUR_unique['Syhtnetic_data_unique_count']*100

print(SIMI_SACT_TUMOUR_unique)

##make frequency tables for SIM I and subsets
def frequency (table, column)
table_column_CODE_FREQ=pd.value_counts(table[column]).to_frame().reset_index()
table_column_CODE_FREQ.columns=[column,'count_synth']

table_50_column_CODE_FREQ=pd.value_counts(table[column]).to_frame().reset_index()
table_50_column_CODE_FREQ.columns=[column,'count_0.50_synth']

table_25_column_CODE_FREQ=pd.value_counts(table[column]).to_frame().reset_index()
table_25_column_CODE_FREQ.columns=[column,'count_0.25_synth']

table_10_column_CODE_FREQ=pd.value_counts(table[column]).to_frame().reset_index()
table_10_column_CODE_FREQ.columns=[column,'count_0.10_synth']

return table_column_CODE_FREQ, table_50_column_CODE_FREQ, table_25_column_CODE_FREQ,table_10_column_CODE_FREQ

frequency()


SIMI_SACT_TUMOUR_CONSULTANT_SPECIALITY_CODE_FREQ=pd.value_counts(SIMI_SACT_TUMOUR['CONSULTANT_SPECIALITY_CODE']).to_frame().reset_index()
SIMI_SACT_TUMOUR_CONSULTANT_SPECIALITY_CODE_FREQ.columns=['CONSULTANT_SPECIALITY_CODE','count_synth']

SIMI_SACT_TUMOUR_50_CONSULTANT_SPECIALITY_CODE_FREQ=pd.value_counts(SIMI_SACT_TUMOUR_50['CONSULTANT_SPECIALITY_CODE']).to_frame().reset_index()
SIMI_SACT_TUMOUR_50_CONSULTANT_SPECIALITY_CODE_FREQ.columns=['CONSULTANT_SPECIALITY_CODE','count_0.50_synth']

SIMI_SACT_TUMOUR_25_CONSULTANT_SPECIALITY_CODE_FREQ=pd.value_counts(SIMI_SACT_TUMOUR_25['CONSULTANT_SPECIALITY_CODE']).to_frame().reset_index()
SIMI_SACT_TUMOUR_25_CONSULTANT_SPECIALITY_CODE_FREQ.columns=['CONSULTANT_SPECIALITY_CODE','count_0.25_synth']

SIMI_SACT_TUMOUR_10_CONSULTANT_SPECIALITY_CODE_FREQ=pd.value_counts(SIMI_SACT_TUMOUR_10['CONSULTANT_SPECIALITY_CODE']).to_frame().reset_index()
SIMI_SACT_TUMOUR_10_CONSULTANT_SPECIALITY_CODE_FREQ.columns=['CONSULTANT_SPECIALITY_CODE','count_0.10_synth']

#

SIMI_SACT_TUMOUR_PRIMARY_DIAGNOSIS_FREQ=pd.value_counts(SIMI_SACT_TUMOUR['PRIMARY_DIAGNOSIS']).to_frame().reset_index()
SIMI_SACT_TUMOUR_PRIMARY_DIAGNOSIS_FREQ.columns=['PRIMARY_DIAGNOSIS','count_synth']

SIMI_SACT_TUMOUR_50_PRIMARY_DIAGNOSIS_FREQ=pd.value_counts(SIMI_SACT_TUMOUR_50['PRIMARY_DIAGNOSIS']).to_frame().reset_index()
SIMI_SACT_TUMOUR_50_PRIMARY_DIAGNOSIS_FREQ.columns=['PRIMARY_DIAGNOSIS','count_0.50_synth']

SIMI_SACT_TUMOUR_25_PRIMARY_DIAGNOSIS_FREQ=pd.value_counts(SIMI_SACT_TUMOUR_25['PRIMARY_DIAGNOSIS']).to_frame().reset_index()
SIMI_SACT_TUMOUR_25_PRIMARY_DIAGNOSIS_FREQ.columns=['PRIMARY_DIAGNOSIS','count_0.25_synth']

SIMI_SACT_TUMOUR_10_PRIMARY_DIAGNOSIS_FREQ=pd.value_counts(SIMI_SACT_TUMOUR_10['PRIMARY_DIAGNOSIS']).to_frame().reset_index()
SIMI_SACT_TUMOUR_10_PRIMARY_DIAGNOSIS_FREQ.columns=['PRIMARY_DIAGNOSIS','count_0.10_synth']

#

SIMI_SACT_TUMOUR_MORPHOLOGY_CLEAN_FREQ=pd.value_counts(SIMI_SACT_TUMOUR['MORPHOLOGY_CLEAN']).to_frame().reset_index()
SIMI_SACT_TUMOUR_MORPHOLOGY_CLEAN_FREQ.columns=['MORPHOLOGY_CLEAN','count_synth']

SIMI_SACT_TUMOUR_50_MORPHOLOGY_CLEAN_FREQ=pd.value_counts(SIMI_SACT_TUMOUR_50['MORPHOLOGY_CLEAN']).to_frame().reset_index()
SIMI_SACT_TUMOUR_50_MORPHOLOGY_CLEAN_FREQ.columns=['MORPHOLOGY_CLEAN','count_0.50_synth']

SIMI_SACT_TUMOUR_25_MORPHOLOGY_CLEAN_FREQ=pd.value_counts(SIMI_SACT_TUMOUR_25['MORPHOLOGY_CLEAN']).to_frame().reset_index()
SIMI_SACT_TUMOUR_25_MORPHOLOGY_CLEAN_FREQ.columns=['MORPHOLOGY_CLEAN','count_0.25_synth']

SIMI_SACT_TUMOUR_10_MORPHOLOGY_CLEAN_FREQ=pd.value_counts(SIMI_SACT_TUMOUR_10['MORPHOLOGY_CLEAN']).to_frame().reset_index()
SIMI_SACT_TUMOUR_10_MORPHOLOGY_CLEAN_FREQ.columns=['MORPHOLOGY_CLEAN','count_0.10_synth']

##merging the frequency tables
CONSULTANT_SPECIALITY_CODE_FREQ_merge=pd.merge(SIMI_SACT_TUMOUR_CONSULTANT_SPECIALITY_CODE_FREQ, SIMI_SACT_TUMOUR_50_CONSULTANT_SPECIALITY_CODE_FREQ, on='CONSULTANT_SPECIALITY_CODE',how='outer')
CONSULTANT_SPECIALITY_CODE_FREQ_merge=pd.merge(CONSULTANT_SPECIALITY_CODE_FREQ_merge, SIMI_SACT_TUMOUR_25_CONSULTANT_SPECIALITY_CODE_FREQ, on='CONSULTANT_SPECIALITY_CODE',how='outer')
CONSULTANT_SPECIALITY_CODE_FREQ_merge=pd.merge(CONSULTANT_SPECIALITY_CODE_FREQ_merge, SIMI_SACT_TUMOUR_10_CONSULTANT_SPECIALITY_CODE_FREQ, on='CONSULTANT_SPECIALITY_CODE',how='outer')
CONSULTANT_SPECIALITY_CODE_FREQ_merge.sort_values(by=['count_synth'],ascending=False)

PRIMARY_DIAGNOSIS_FREQ_merge=pd.merge(SIMI_SACT_TUMOUR_PRIMARY_DIAGNOSIS_FREQ, SIMI_SACT_TUMOUR_50_PRIMARY_DIAGNOSIS_FREQ, on='PRIMARY_DIAGNOSIS',how='outer')
PRIMARY_DIAGNOSIS_FREQ_merge=pd.merge(PRIMARY_DIAGNOSIS_FREQ_merge, SIMI_SACT_TUMOUR_25_PRIMARY_DIAGNOSIS_FREQ, on='PRIMARY_DIAGNOSIS',how='outer')
PRIMARY_DIAGNOSIS_FREQ_merge=pd.merge(PRIMARY_DIAGNOSIS_FREQ_merge, SIMI_SACT_TUMOUR_10_PRIMARY_DIAGNOSIS_FREQ, on='PRIMARY_DIAGNOSIS',how='outer')
PRIMARY_DIAGNOSIS_FREQ_merge.sort_values(by=['count_synth'],ascending=False)

MORPHOLOGY_CLEAN_FREQ_merge=pd.merge(SIMI_SACT_TUMOUR_MORPHOLOGY_CLEAN_FREQ, SIMI_SACT_TUMOUR_50_MORPHOLOGY_CLEAN_FREQ, on='MORPHOLOGY_CLEAN',how='outer')
MORPHOLOGY_CLEAN_FREQ_merge=pd.merge(MORPHOLOGY_CLEAN_FREQ_merge, SIMI_SACT_TUMOUR_25_MORPHOLOGY_CLEAN_FREQ, on='MORPHOLOGY_CLEAN',how='outer')
MORPHOLOGY_CLEAN_FREQ_merge=pd.merge(MORPHOLOGY_CLEAN_FREQ_merge, SIMI_SACT_TUMOUR_10_MORPHOLOGY_CLEAN_FREQ, on='MORPHOLOGY_CLEAN',how='outer')
MORPHOLOGY_CLEAN_FREQ_merge.sort_values(by=['count_synth'],ascending=False)

                         Item  Syhtnetic_data_unique_count  \
0           PRIMARY_DIAGNOSIS                          760
1  CONSULTANT_SPECIALITY_CODE                           76
2            MORPHOLOGY_CLEAN                          533

   0.50_Syhtnetic_data_unique_count  0.25_Syhtnetic_data_unique_count  \
0                               683                               594
1                                67                                62
2                               469                               416

   0.10_Syhtnetic_data_unique_count  Missing_values_0.50_count  \
0                               498                         77
1                                55                          9
2                               319                         64

   Missing_values_0.50_percentage  Missing_values_0.25_count  \
0                       10.131579                        166
1                       11.842105                         14
2                       12.007505                        117

   Missing_values_0.25_percentage  Missing_values_0.10_count  \
0                       21.842105                        262
1                       18.421053                         21
2                       21.951220                        214

   Missing_values_0.10_percentage
0                       34.473684
1                       27.631579
2                       40.150094

,MORPHOLOGY_CLEAN,count_synth,count_0.50_synth,count_0.25_synth,count_0.10_synth
0,81403.0,42021,21044.0,10426.0,4127.0
1,85003.0,22888,11407.0,5755.0,2253.0
2,80703.0,9867,4959.0,2524.0,974.0
3,97323.0,5912,2964.0,1470.0,625.0
4,80103.0,5373,2711.0,1339.0,541.0
...,...,...,...,...,...
482,92433.0,1,NaN,NaN,1.0
481,91503.0,1,1.0,NaN,NaN
480,80136.0,1,NaN,NaN,NaN
479,95803.0,1,1.0,NaN,NaN
532,85811.0,1,1.0,NaN,NaN

In [5]:
SIMI_SACT_TUMOUR['MERGED_PATIENT_ID'].value_counts()

20012048     15
20115348     14
140026158    14
60046535     13
40098249     13
             ..
30101747      1
40007850      1
40085740      1
190025963     1
180012105     1
Name: MERGED_PATIENT_ID, Length: 190351, dtype: int64

In [6]:
SIMI_SACT_TUMOUR[SIMI_SACT_TUMOUR['MERGED_PATIENT_ID']==20012048]

,MERGED_TUMOUR_ID,MERGED_PATIENT_ID,CONSULTANT_SPECIALITY_CODE,PRIMARY_DIAGNOSIS,MORPHOLOGY_CLEAN
35599,20028496,20012048,370.0,C509,85003.0
35600,20028497,20012048,800.0,C509,NaN
35601,20028498,20012048,800.0,C509,85003.0
35602,20028499,20012048,800.0,C509,NaN
35603,20028500,20012048,370.0,C509,80103.0
35604,20028501,20012048,370.0,C509,NaN
35605,20028502,20012048,800.0,C509,NaN
35606,20028503,20012048,800.0,C509,NaN
35607,20028504,20012048,800.0,C504,85003.0
35608,20028505,20012048,800.0,C504,85003.0
35609,20028506,20012048,800.0,C509,NaN
35610,20028507,20012048,800.0,C509,NaN
35611,20028508,20012048,800.0,C509,NaN
57243,20051494,20012048,800.0,C509,85223.0
59401,20064976,20012048,800.0,C509,NaN