In [61]:
import pandas as pd
import datetime as dt
import matplotlib.pyplot as plt
import seaborn as sns

## Import observations here: --------------------------------------------------------------------------
df = pd.read_csv('../isaFull.tsv', '\t')
# df = df[['Participant_Id', 'Visit date [EUPATH_0000091]']] # pick features
df = df.dropna(subset=['Visit date [EUPATH_0000091]'])
df['Visit date [EUPATH_0000091]'] = pd.to_datetime(df['Visit date [EUPATH_0000091]'])

## Create visit week column containing date on MONDAY of the week the visit took place in: -------------
df['Visit week'] = df['Visit date [EUPATH_0000091]'].apply(lambda d: d-dt.timedelta(days=d.weekday()))
#print(df)

## Group by participant then by visit week: -----------------------------------------------------------
index = pd.MultiIndex.from_frame(df[['Visit week', 'Participant_Id']])
df = df.set_index(index)
# df = df.drop(columns=['Participant_Id', 'Visit week'])
df['counts'] = df.groupby(level=['Visit week', 'Participant_Id']).size()
df = df.sort_index()
df_2 = df[df['counts']==2]
df_2.index = range(len(df_2))

                           Observation_Id  Participant_Id Household_Id  \
Visit week Participant_Id
2011-07-25 1008                 100818844            1008  HH216001607
           1008                 100818845            1008  HH216001607
2011-08-01 1017                 101718845            1017  HH214000507
           1017                 101718851            1017  HH214000507
           1018                 101818845            1018  HH221002517
...                                   ...             ...          ...
2017-06-19 3399                 339920992            3399  HH117009902
2017-06-26 3419                 341921000            3419  HH114006801
           3419                 341920997            3419  HH114006801
           3470                 347020998            3470  HH134001001
           3470                 347020999            3470  HH134001001

                          Abdominal pain [HP_0002027]  \
Visit week Participant_Id
2011-07-25 1008                                    No
           1008                                    No
2011-08-01 1017                                    No
           1017                                    No
           1018                                   Yes
...                                               ...
2017-06-19 3399                                    No
2017-06-26 3419                                   Yes
           3419                                    No
           3470                                    No
           3470                                    No

                           Abdominal pain duration (days) [EUPATH_0000154]  \
Visit week Participant_Id
2011-07-25 1008                                                        0.0
           1008                                                        0.0
2011-08-01 1017                                                        0.0
           1017                                                        0.0
           1018                                                        1.0
...                                                                    ...
2017-06-19 3399                                                        0.0
2017-06-26 3419                                                        1.0
           3419                                                        0.0
           3470                                                        0.0
           3470                                                        0.0

                          Admitting hospital [EUPATH_0000318]  \
Visit week Participant_Id
2011-07-25 1008                                           NaN
           1008                                           NaN
2011-08-01 1017                                           NaN
           1017                                           NaN
           1018                                           NaN
...                                                       ...
2017-06-19 3399                                           NaN
2017-06-26 3419                                           NaN
           3419                                           NaN
           3470                                           NaN
           3470                                           NaN

                           Age at visit (years) [EUPATH_0000113]  \
Visit week Participant_Id
2011-07-25 1008                                            34.16
           1008                                            34.16
2011-08-01 1017                                             4.11
           1017                                             4.13
           1018                                            39.40
...                                                          ...
2017-06-19 3399                                             4.78
2017-06-26 3419                                             9.16
           3419                                             9.15
           3470                                             4.04
           3470                                             4.04

                          Anorexia [SYMP_0000523]  \
Visit week Participant_Id
2011-07-25 1008                                No
           1008                                No
2011-08-01 1017                                No
           1017                                No
           1018                                No
...                                           ...
2017-06-19 3399                                No
2017-06-26 3419                                No
           3419                                No
           3470                                No
           3470                                No

                           Anorexia duration (days) [EUPATH_0000155]  \
Visit week Participant_Id
2011-07-25 1008                                                  0.0
           1008                                                  0.0
2011-08-01 1017                                                  0.0
           1017                                                  0.0
           1018                                                  0.0
...                                                              ...
2017-06-19 3399                                                  0.0
2017-06-26 3419                                                  0.0
           3419                                                  0.0
           3470                                                  0.0
           3470                                                  0.0

                           Asexual Plasmodium parasite density, by microscopy [EUPATH_0000092]  \
Visit week Participant_Id
2011-07-25 1008                                                          0.0
           1008                                                          0.0
2011-08-01 1017                                                          0.0
           1017                                                          NaN
           1018                                                          0.0
...                                                                      ...
2017-06-19 3399                                                          NaN
2017-06-26 3419                                                      22480.0
           3419                                                        192.0
           3470                                                          0.0
           3470                                                          0.0

                           ... Subjective fever [EUPATH_0000100]  \
Visit week Participant_Id  ...
2011-07-25 1008            ...                                No
           1008            ...                               Yes
2011-08-01 1017            ...                                No
           1017            ...                                No
           1018            ...                                No
...                        ...                               ...
2017-06-19 3399            ...                                No
2017-06-26 3419            ...                               Yes
           3419            ...                                No
           3470            ...                                No
           3470            ...                               Yes

                          Submicroscopic Plasmodium present, by LAMP [EUPATH_0000487]  \
Visit week Participant_Id
2011-07-25 1008                                                     Negative
           1008                                                          NaN
2011-08-01 1017                                                     Negative
           1017                                                          NaN
           1018                                                     Negative
...                                                                      ...
2017-06-19 3399                                                          NaN
2017-06-26 3419                                                          NaN
           3419                                                          NaN
           3470                                                     Negative
           3470                                                          NaN

                          Temperature (C) [EUPATH_0000110]  \
Visit week Participant_Id
2011-07-25 1008                                       37.7
           1008                                       37.2
2011-08-01 1017                                       36.9
           1017                                       36.6
           1018                                       37.4
...                                                    ...
2017-06-19 3399                                       36.6
2017-06-26 3419                                       38.7
           3419                                       36.8
           3470                                       37.4
           3470                                       37.1

                          Visit date [EUPATH_0000091]  \
Visit week Participant_Id
2011-07-25 1008                            2011-07-29
           1008                            2011-07-30
2011-08-01 1017                            2011-08-01
           1017                            2011-08-07
           1018                            2011-08-04
...                                               ...
2017-06-19 3399                            2017-06-20
2017-06-26 3419                            2017-06-29
           3419                            2017-06-26
           3470                            2017-06-26
           3470                            2017-06-27

                           Visit type [EUPATH_0000311]  Vomiting [HP_0002013]  \
Visit week Participant_Id
2011-07-25 1008                             Enrollment                     No
           1008                      Unscheduled visit                     No
2011-08-01 1017                             Enrollment                     No
           1017                      Unscheduled visit                     No
           1018                             Enrollment                     No
...                                                ...                    ...
2017-06-19 3399                      Unscheduled visit                     No
2017-06-26 3419                      Unscheduled visit                     No
           3419                        Scheduled visit                     No
           3470                        Scheduled visit                     No
           3470                      Unscheduled visit                     No

                          Vomiting duration (days) [EUPATH_0000165]  \
Visit week Participant_Id
2011-07-25 1008                                                 0.0
           1008                                                 0.0
2011-08-01 1017                                                 0.0
           1017                                                 0.0
           1018                                                 0.0
...                                                             ...
2017-06-19 3399                                                 0.0
2017-06-26 3419                                                 0.0
           3419                                                 0.0
           3470                                                 0.0
           3470                                                 0.0

                          Weight (kg) [EUPATH_0000732]  Visit week counts
Visit week Participant_Id
2011-07-25 1008                                   80.0  2011-07-25      2
           1008                                    NaN  2011-07-25      2
2011-08-01 1017                                   19.0  2011-08-01      2
           1017                                   18.5  2011-08-01      2
           1018                                   85.0  2011-08-01      2
...                                                ...         ...    ...
2017-06-19 3399                                    NaN  2017-06-19      2
2017-06-26 3419                                    NaN  2017-06-26      2
           3419                                   25.0  2017-06-26      2
           3470                                   14.0  2017-06-26      2
           3470                                    NaN  2017-06-26      2

[1956 rows x 56 columns]

In [96]:
import pdb;
other_array = []
for index, row in df_2.iterrows():
    data = df_2[ df_2['Visit week']==row['Visit week'] ]\
                [ df_2['Participant_Id']==row['Participant_Id'] ].reset_index(drop=True)
#     pdb.set_trace()
    if len(data)!=2:
        print(len(data))
        pdb.set_trace()
    array = []
    for column in df_2.columns:
        array.append(data.iloc[0][column] == data.iloc[1][column])
    other_array.append(array)

/Users/noorashbass/opt/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """

In [99]:
dataframe_true_false = pd.DataFrame(other_array, columns=df_2.columns)
dataframe_true_false

,Observation_Id,Participant_Id,Household_Id,Abdominal pain [HP_0002027],Abdominal pain duration (days) [EUPATH_0000154],Admitting hospital [EUPATH_0000318],Age at visit (years) [EUPATH_0000113],Anorexia [SYMP_0000523],Anorexia duration (days) [EUPATH_0000155],"Asexual Plasmodium parasite density, by microscopy [EUPATH_0000092]",...,Subjective fever [EUPATH_0000100],"Submicroscopic Plasmodium present, by LAMP [EUPATH_0000487]",Temperature (C) [EUPATH_0000110],Visit date [EUPATH_0000091],Visit type [EUPATH_0000311],Vomiting [HP_0002013],Vomiting duration (days) [EUPATH_0000165],Weight (kg) [EUPATH_0000732],Visit week,counts
0,False,True,True,True,True,False,True,True,True,True,...,False,False,False,False,False,True,True,False,True,True
1,False,True,True,True,True,False,True,True,True,True,...,False,False,False,False,False,True,True,False,True,True
2,False,True,True,True,True,False,False,True,True,False,...,True,False,False,False,False,True,True,False,True,True
3,False,True,True,True,True,False,False,True,True,False,...,True,False,False,False,False,True,True,False,True,True
4,False,True,True,False,False,False,False,True,True,False,...,True,False,False,False,False,True,True,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1951,False,True,True,True,True,False,False,True,True,False,...,True,False,False,False,False,True,True,False,True,True
1952,False,True,True,False,False,False,False,True,True,False,...,False,False,False,False,False,True,True,False,True,True
1953,False,True,True,False,False,False,False,True,True,False,...,False,False,False,False,False,True,True,False,True,True
1954,False,True,True,True,True,False,True,True,True,True,...,False,False,False,False,False,True,True,False,True,True
1955,False,True,True,True,True,False,True,True,True,True,...,False,False,False,False,False,True,True,False,True,True